### ISSUE TITLE
What architecture can this library build?

### ISSUE THREAD

**Issue by KentaroJay** [markfinger/python-react#102]
Hi, I'm Kentaro from Japan.
I'm looking for lib that can build so-called 'hybrid architecture'. (reference : https://fractalideas.com/blog/making-react-and-django-play-well-together/)

If you don't mind, I would like you to tell me which architecture(according to the link above) can this lib build.

Thank you.

**Comment by mic159** [comment]
Broadly speaking it's number 2.
Django serves all requests, and when it's for a dynamic page, it requests the frontend from the node server.
Static files are directly served from Django (however you want, maybe with white noise), but the HTML pages are proxies through to the nodejs server to render react pages.

Technically, the nodejs server only renders the app section of the don, and Django still stitches that into the full html page.

**Comment by KentaroJay** [comment]
Thank you for the immediate reply!

> Static files are directly served from Django (however you want, maybe with white noise), but the HTML pages are proxies through to the nodejs server to render react pages.

Isn't it possible for static files to be served, by configuring settings.py, from nginx, or aws s3 (in production)?

**Comment by mic159** [comment]
> > Static files are directly served from Django (however you want, maybe with white noise), but the HTML pages are proxies through to the nodejs server to render react pages.
> 
> Isn't it possible for static files to be served, by configuring settings.py, from nginx, or aws s3 (in production)?

Yes, static files can be done in any way that Django supports.

This project is about the HTML pages, and should not affect how you serve static assets.

The requests for HTML pages come to Django, and your python code then sends the request onto the NodeJS server to render the react frontend.

**Comment by KentaroJay** [comment]
OK! I got it very well!
tkank you for your replies!
@mic159 @
