### ISSUE TITLE
Unexpected token in component

### ISSUE THREAD

**Issue by hizneway** [markfinger/python-react#104]
Do you know why this may be happening?

Stack trace: SyntaxError: {mypath}/index.jsx: Unexpected token (6:3)
 
``` 4 | 	render() {
  5 | 		return (
> 6 | 			<div>
    | 			^
  7 | 				hello!
  8 | 			</div>
  9 | 		);```

**Comment by markfinger** [comment]
It usually means the renderer isn't running compiled JSX. The JSX format isn't executable in a JS engine natively, so you need to either run something like the babel loader (which compiles them on demand) or precompile with something like webpack/vite/etc.

**Comment by hizneway** [comment]
Thanks for the quick reply. That makes sense. I was able to get it working.
