### ISSUE TITLE
Cannot log from react

### ISSUE THREAD

**Issue by fellu** [markfinger/python-react#38]
Hi,

using python-react with js-host, how can I log from react that being rendred in backend. Also using Django. Trying with console.log but nothing appears.

JS_HOST = {
    'USE_MANAGER': DEBUG,
    'VERBOSITY': 600
}
REACT = {
    'DEVTOOL': 'eval' if DEBUG else None,
}

**Comment by markfinger** [comment]
I assume that js-host is running under a manager. The easiest way is to spin up the manager manually, so you'll get all the terminal output. Refer to https://github.com/markfinger/js-host#cli-usage

It boils down to
```
node_modules/.bin/js-host host.config.js
```

**Comment by markfinger** [comment]
Correction: ... easiest way is to spin up the <strike>manager</strike> host manually...
