### ISSUE TITLE
.babelrc not configured correctly in project example

### ISSUE THREAD

**Issue by Pringels** [markfinger/python-react#53]
In the basic rendering example the provided .jsx files make use of es6 syntax.
However the `.babelrc` configuration does not include an es6 compiler plugin. 

I propose adding `"presets": ["es2015"]` to the config.

**Comment by markfinger** [comment]
Sure, sounds great.

Can you open a PR?

**Comment by Pringels** [comment]
Sure :)

**Comment by Pringels** [comment]
Some of the React code used in the examples is also deprecated. Will include fixes for those in my PR

**Comment by markfinger** [comment]
Cool, thanks for looking into it.

Some of that code has been around for quite a while and is undoubtedly lagging, so feel free to make any changes you deem appropriate :+1:

**Comment by markfinger** [comment]
Closed by #55
