### ISSUE TITLE
missing babel-preset-es2015 in package.json in Tornado-example

### ISSUE THREAD

**Issue by letfly** [markfinger/python-react#58]
Hi,error:
/../python-react/examples/Tornado-example/static/js/CommentBox.jsx:1
(function (exports, require, module, __filename, __dirname) { import React fro
There should add babel-preset-es2015 in package.json and presets in .babelrc.

**Comment by markfinger** [comment]
Thanks. Can you open a pull request to add those lines?

**Comment by letfly** [comment]
But I haven't permission to push a branch.
