### ISSUE TITLE
Issue with _PROXY_DJANGO_SETTINGS?

### ISSUE THREAD

**Issue by BenAtEventbrite** [markfinger/python-react#61]
The [docs](https://github.com/markfinger/python-react#settings) say that I can add settings for `RENDER` & `RENDER_URL`, but it's not working. I've traced it down to [`conf.py`](https://github.com/markfinger/python-react/blob/master/react/conf.py#L9) and the `_PROXY_DJANGO_SETTINGS` private variable.

It's initialized to `False`, but there's no way to to set it `True`. So in [`RENDER_URL`](https://github.com/markfinger/python-react/blob/master/react/conf.py#L13-L14) & [`RENDER`](https://github.com/markfinger/python-react/blob/master/react/conf.py#L25-L26) it always returns the default settings `_render_url` & `_render`.

My current workaround is to call [`configure`](https://github.com/markfinger/python-react/blob/master/react/conf.py#L35-L39) directly so that I can override the defaults:

```python
from react import conf
from django.conf import settings
conf.settings.configure(settings.REACT.get('RENDER_URL'), settings.REACT.get('RENDER'))
```

...but this seems wrong. Am I missing something?

Thanks for the library BTW!

**Comment by markfinger** [comment]
`_PROXY_DJANGO_SETTINGS` should be set to true when django inits the app: https://github.com/markfinger/python-react/blob/78deb9479a302ce226dd5b24c0aaeabe0ebd79ad/react/apps.py#L10

If you're using an older version of django that doesn't support app config, you may want to run the following at some point.

```python
react.conf.settings._PROXY_DJANGO_SETTINGS = True
react.conf.settings.configure(
    **getattr(settings, 'REACT', {})
)
```

If you need to do that, make sure you don't import react.conf until your settings module has completed, somewhere in your views or urls would work. 

There are layers that provide optional django support and they try to import the settings module as a test to detect if django is active. If you import react.conf.settings, you'll trigger a circular import and those layers will silently fail and assume django isn't running.

**Comment by BenAtEventbrite** [comment]
Thanks for the explanation. I did it in the urls and that seems to work. 

I skipped setting `react.conf.settings._PROXY_DJANGO_SETTINGS = True` because when I call `react.conf.settings.configure` that just changes the local values anyway. It feels dirty (to me) to be setting `_PROXY_DJANGO_SETTINGS` outside of the `conf` object since it's intended to be private.
