### ISSUE TITLE
Web2Py support: ImportError('No module named react.render',)

### ISSUE THREAD

**Issue by Anima-t3d** [markfinger/python-react#70]
Does this work with Web2Py? I am relatively new to python and Web2Py. I want to implement react server side rendering in an existing Web2Py application.

I tried the following on a local instance:
`pip install react` and created `modules/react_test.py`:

```python
from react.render import render_component

def test_render(url):
	return render_component('../react/Url.jsx', {'arg': url})

```
It will give an error `﻿﻿﻿ImportError('No module named react.render',)`. 
Did I do something wrong or is it because I am trying to use `python-react` with Web2Py?

Thanks in advance.

**Comment by markfinger** [comment]
Hi,

There's no obvious reason why Web2Py would be the problem. My guess would be `PYTHONPATH` issues in your setup.

Can you provide more detail, e.g.:
-What OS are you on? What python version?
- What command are you using to start the python process?
- If you start a python interpreter, with just `python`, then run `import react`. What happens? If it works, can you try `react.__file__`?

For context, my suspicion here is that either your python setup is broken (and the interpreter can't find the libraries), or you may need to run a different command to start the process.

**Comment by Anima-t3d** [comment]
**What OS and version are you on? What python version (python --version)?**
I am running a local instance of the web2py app on mac OS X El Capitan 10.11.6. With Python 2.7.10

**What command are you using to start the python process?**
I use the [bundled web2py app](http://www.web2py.com/examples/static/web2py_osx.zip) to start the server and modify it through the browser.

**If you start a python interpreter with just python, then run import react. What happens?** **If it works, can you try react.__file__?**

```
$ python
[TEXT HERE]
>>> import react
>>> react.__file__
'/Library/Python/2.7/site-packages/react/__init__.pyc'
```

It seems that when I run the app it doesn't get access to the react file. Could it be solved by copying or symlinking to this file inside the` /Users/XXX/Documents/web2py/web2py.app/Contents/Resources/applications/react_test/modules` or like you mentioned do something with the `PYTHONPATH`

I am first trying it out on a local instance, but once I get it working it will be deployed on a CentOS server.

**Comment by markfinger** [comment]
Adding `'/Library/Python/2.7/site-packages'` to your PYTHONPATH may help. Manipulating the PYTHONPATH during init is a common practice to target source roots, but targeting an interpreter's site-packages is a bit odd.

I haven't looked at the zip you linked, but my guess is that the web2py app is using its own python interpreter, not your system or venv binary. If you check the web2py docs, they might have instructions for how to install libraries within their system.

**Comment by Anima-t3d** [comment]
Thanks for the reply, based on your input I found the [Third party modules chapter in the documentation](http://web2py.com/book/default/chapter/04#Third-party-modules):

> web2py is written in Python, so it can import and use any Python module, including third party modules. It just needs to be able to find them. As with any Python application, modules can be installed in the official Python "site-packages" directory, and they can then be imported from anywhere inside your code.
> 
> Modules in the "site-packages" directory are, as the name suggests, site-level packages. Applications requiring site-packages are not portable unless these modules are installed separately. The advantage of having modules in "site-packages" is that multiple applications can share them.

I will give that a try tomorrow and update here.

**Comment by markfinger** [comment]
No worries, best of luck with it.

I think there's a way for pip to install locally, something like `pip install react --target /path/to/dir` which should create a directory called `react` that contains the library). Might be of use to workaround web2py's quirks as you could now use relative imports, eg: `from .react.render import ...`.

**Comment by Anima-t3d** [comment]
The local install into the modules folder worked. However I have this `<class 'react.exceptions.ComponentSourceFileNotFound'>` thrown by the [render_component function](https://github.com/markfinger/python-react/blob/master/react/render.py#L7) 

If I try to do the Web2Py way of [the basic example](https://github.com/markfinger/python-react/blob/master/examples/basic_rendering/example.py#L14-L21):
```python
...
rendered = render_component(
        os.path.join(os.getcwd(), 'static', 'js', 'CommentBox.jsx'),
        {
            'comments': comments,
            'url': '/comment/',
        },
        to_static_markup=True,
)
...
```
```python
...
rendered = render_component(
        # '../static/CommentBox.jsx',
        # OR
        URL('static','CommentBox.jsx'),
        {
            'comments': comments,
            'url': '/comment/',
        },
        to_static_markup=True,
)
...
```
I get the above error. So it seems that in Web2Py my urls are not pointing to the file correctly. I tried relative and absolute both in different and same folder. In the end I got it working by using:
```python
rendered = render_component(os.path.dirname(os.path.abspath(__file__)) + '/CommentBox.jsx', {'comments': comments, 'url': '/comment/'})
```
Any ideas on where I can look to find the issue?

**Comment by markfinger** [comment]
The path provided to the renderer needs to be an absolute path to the file, so your last example should work fine.

I usually have something like

```python
ROOT = os.path.dirname(__file__)

# ...

rendered = render_component(
    os.path.join(ROOT, 'path', 'to', 'CommentBox.jsx'), 
    {'comments': comments, 'url': '/comment/'}
)
```

**Comment by Anima-t3d** [comment]
I see, for it to work properly I need to place the templates in a sub folder. I was thinking to use it as:
```
|-views
|-modules (which would point to the jsx which would be inside the views directory)
```
Any idea what is wrong with the jsx file? Is it my babel not configured correctly or is something up with the file? As far as I can tell the syntax is correct?

**Comment by markfinger** [comment]
Hard to tell with the encoding artifacts, but I'd guess that it hasn't installed the jsx plugin. You'll need to make sure that the `.babelrc` file is in the same (or maybe higher, not sure though) dir as the render server's script.

**Comment by Anima-t3d** [comment]
Thanks. I finally managed it to show up. It was indeed the fact that `.babelrc` was not in the _bloodline_ directory that the template would look for. As stated in [the babel docs](https://babeljs.io/docs/usage/babelrc/):

> Babel will look for a .babelrc in the current directory of the file being transpiled. If one does not exist, it will travel up the directory tree until it finds either a .babelrc, or a package.json with a "babel": {} hash within.

I will update this answer with the final setup so other people using web2py would have a better insight in how to get react working. For now I consider this closed, but I will close it once I get it fully working inclusive of front-end react mounting (like attaching events).

**Comment by markfinger** [comment]
Thanks for the write-up, @Anima-t3d. 

I've added a FAQ section to the docs and linked to your above comment.

https://github.com/markfinger/python-react/blob/master/README.md#can-python-react-integrate-with-web2py
