### ISSUE TITLE
Error trying to use Tornado Example

### ISSUE THREAD

**Issue by ideletemyself** [markfinger/python-react#72]
I keep getting this error when I try to use the Tornado example you've provided:

`TypeError: Object of type 'bytes' is not JSON serializable`

Any assistance would be very appreciated...

**Comment by markfinger** [comment]
Are you able to provide the full stack trace of the error?

Off the top of my head, I presume there's a type coercion or string encoding that's missing and it's blowing up in python 3. Unfortunately, I'm not familiar with the tornado code, as it was contributed by @abdelouahabb.

**Comment by ideletemyself** [comment]
It's cool, I actually found another project on GitHub that eventually led to me getting Tornado & React to play nicely. Thank you for your assistance though!
